= Documentation
:toc:
:toc-title:
:toclevels: 3

== Introduction

To communicate with the server, a client needs to use both REST and
WebSocket. WebSocket is used for quasi-realtime communication (sending
and receiving messages and chat rooms), while the rest of the tasks are
performed using the REST-ish API (log in, register, file upload, etc.).
Documentation for the REST part is provided using Swagger and can be
viewed by visiting `localhost:8000/api` on a running server.

== WebSocket communication

=== Step 1: Connection

To start communicating with the server using WebSocket, a connection
needs to be opened to an address as per the format provided below.

....
ws://<server address>:8000/<token>/<last room>/<last message>/
....

Trying to connect to server without providing all the information
specified above will result in server rejecting the connection request
without much delay, so let’s take a look at the things in the pointy
brackets.

* `server address`: Can be the IP address of the server in the local
network or its publicly visible IP address or domain name, in case you
did all the plumbing necessary for that. You might want to have the
server address configurable and stored in your application’s settings,
especially in case of a local deployment.
* `token`: Authentication token. Should be stored on the device memory
after retrieving it the first time using log in or register REST API
endpoints.
* `last room`: Server ID of the last room received via WebSocket. Set to
`-1` if not initialized yet. Should be stored on the device memory.
* `last message`: Server ID of the last message received via WebSocket.
Set to `-1` if not initialized yet. Should be stored on the device
memory.

Once both last room and last message server IDs are defined, only the
newer one should be passed, while the other should be set to `-1` when
connecting to server. Determining which one is newer should be performed
based on the creation times of each of them. Server will use provided
data to synchronize the device with the current server state,
i.e. resend all the room and message creation notifications the client
device has missed since the last time it connected to the server, based
on the last room or message ID provided.

=== Step 2: Creating a room

A room creation request is a JSON object and it follows the structure
below.

[source,json]
----
{
    "type": "create",
    "attr": {
        "object": "room",
        "sender_unique": "exampleuser_aBc0",
        "name": "Example room",
        "participants": [0, 7, 42, 9000]
    }
}
----

* `type`: String describing the message type, or rather, action. This is
a creation request, so the type should be `create`, the only valid type
when sending requests from the client to the server.
* `attr`: Attributes. All sorts of data the server and other clients
might care of.
** `object`: We’re creating a room, so `room` goes here. If this was a
message creation request, we’d specify `message` instead.
** `sender_unique`: Unique identifier of the sender device. Used to
distinguish the device from other devices connected to the server,
including other devices of the same user when receiving notifications.
Should follow the `<username>_<four random a-zA-Z0-9 characters>` form.
** `name`: Room name. Should contain between 1 and 255 characters.
** `participants`: An array of integers, where each number represents a
user ID of a participant. Should contain the creator’s ID as well. Does
not have to be sorted. Each room must have at least two participants,
so, apart from the creator’s ID, at least one new ID should be provided.

==== Responses and notifications

Once a room creation request is successfully processed, the server send
the sender a response, and all the clients connected to the WebSocket
server are sent a copy of the created room in the form of a
notification.

Response is a copy of received room data as well, but it contains less
data than the notification. Received response data should be used for:

* storing the room in device’s database,
* updating synchronization data used in Step 1 and
* if visible, updating chat room list.

Structure of a response to a room creation request is shown below.

[source,json]
----
{
    "type": "response",
    "attr": {
        "object": "room",
        "name": "Example room",
        "id": 9,
        "time": 1536809666507.053
    }
}
----

* `type`: The action conveyed by this message is a response, and thus
its value is `response`.
* `attr`: Response attributes sent only to the sender.
** `object`: This is a response to a room creation request and because
of that, the value of this attribute is `room`.
** `name`: Name of the created room.
** `id`: ID of the room on server.
** `time`: Room creation time described in milliseconds since the Unix
epoch. Along with `id`, one of crucial parts of the synchronization
procedure outlined in Step 1. If greater than the time created of the
last room stored, stored room ID and creation time should be replaced by
data received in this response. Should be used in sorting chat rooms as
well.

Structure of a notification for a newly created room is given below.

[source,json]
----
{
    "type": "notification",
    "attr": {
        "object": "room",
        "name": "Example room",
        "id": 9,
        "sender": "exampleuser",
        "sender_id": 42,
        "sender_unique": "exampleuser_aBc0",
        "participants": [0, 7, 42, 9000],
        "time": 1536809666507.053
    }
}
----

* `type`: Action conveyed by the message, in this case `notification`.
One of two valid `type` values for messages sent from the server to
clients along with `response`.
* `attr`: Notification attributes sent to all client devices on server.
** `object`: String describing the type of the object the notification
is about, in this case `room`.
** `name`: Name of the created room.
** `id`: Server ID of the created room. Used for synchronization and
sorting purposes.
** `sender`: String containing the name of the user who created the
room. Useful for showing in notifications.
** `sender_id`: Server ID of the creator. Useful when determining
whether a notification should be shown depending on whether the room
originates from a completely different user.
** `sender_unique`: Unique sender device identifier. Should be used to
ignore the notification on the device the room was created on, as it has
already received all the necessary room details from the response.
** `participants`: If the `sender_unique` value is different from the
client device’s value, this is used to determine whether the
notification is relevant to the device and its owner.
** `time`: Room creation time. Used for synchronization and sorting
purposes.

=== Step 3: Sending a message

Sending a message is done using WebSocket protocol, so its creation
request bears some resemblances to the room creation request, but it
adds some REST action as well. As all famous platforms for chatting come
with the feature of exchanging files, Flack had to feature it as well.
To add a file to a message, before sending a message creation request
via WebSocket, the file needs to be uploaded using the file upload REST
endpoint. The endpoint should return, among other data, the server ID of
the uploaded file. Returned data can be stored on the device to later
share the file in multiple chat rooms.

Also, if the sender feels like that, they should be able to share their
location.

Structure of the message creation request is given below.

[source,json]
----
{
    "type": "create",
    "attr": {
        "object": "message",
        "sender_unique": "exampleuser_aBc0",
        "content": "Hello world!",
        "file": 123,
        "room": 9,
        "location": {
            "latitude": 30.1234567,
            "longitude": 40.1234567
        }
    }
}
----

* `type`: String describing the action requested. As mentioned in the
room creation request in Step 1, the only valid value here for clients
is `create`.
* `attr`: An object containing attributes needed for the server to
process and forward to other devices.
** `object`: Being a message creation request, the value here is
`message`.
** `sender_unique`: Unique identifier of the sender device.
** `content`: Text of the message that is to be sent.
** `file`: Server ID of the file uploaded earlier. If no file is
attached to the message, this value should be `null`.
** `room`: Server ID of the room the message should be put into.
** `location`: A child JSON object containing coordinates describing
sender’s location retrieved via device’s built-in location methods. Has
two float attributes, `latitude` and `longitude`. If no location is
provided, set `location` to `null`.

==== Responses and notifications

Assuming that the file has been successfully uploaded and the message
successfully stored and forwarded to all the concerned parties, er,
clients, let’s examine the response and notification objects. In this
case, the response will carry the same data as the notification.

Their structure is given below.

[source,json]
----
{
    "type": "response",
    "attr": {
        "object": "message",
        "content": "Hello world!",
        "file": {
            "name": "examplefile.ext",
            "hash": "Qm1234567890abcdefghijklmnopqrstuvwxyzABCDEFGH",
            "url": "https://ipfs.io/ipfs/Qm1234567890abcdefghijklmnopqrstuvwxyzABCDEFGH/examplefile.ext"
        },
        "room": 9,
        "room_name": "Example room",
        "room_participants": [0, 7, 42, 9000],
        "sender": "exampleuser",
        "sender_id": 42,
        "sender_unique": "exampleuser_aBc0",
        "location": {
            "latitude": 30.1234567,
            "longitude": 40.1234567
        },
        "message_id": 88,
        "time": 1536809666507.053
    }
}
----

* `type`: String descriptor of the message type. Being a message sent
from server to clients, it can have a `response` or `notification`
value.
* `attr`: Attributes used for storage and filtering.
** `object`: Type of the object sent, be it as part of a response, or a
notification. In step 2 we had a `room` here, now it’s a `message`.
** `content`: Content of the message sent.
** `file`: A child object carrying relevant data about the file
attached. If no file is attached, the value of this attribute is `null`.
Contains three attributes: `name` - the attached file’s name; `hash` -
IPFS multihash of the attached file, usable in redistribution outside of
Flack and `url` - URL of the shared file on public IPFS gateway.
** `room`: Server ID of the room the message belongs in.
** `room_name`: Name of the room the message belongs in. Used to easily
construct notifications.
** `room_participants`: Array of participant user IDs. Used to easily
filter irrelevant notifications.
** `sender`: Name of the message sender.
** `sender_id`: Server ID of the user. Used to determine whether to
create a notification or just silently add the received message to the
database and, if applicable, interface.
** `sender_unique`: Unique identifier of the sender device.
** `location`: Child object containing location data. Has a `null` value
if not set.
** `message_id`: Server ID of the message received.
** `time`: Message creation time on server. Used for sorting and
synchronization along with `message_id`.
