# Generated by Django 2.1 on 2018-08-24 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
