# Generated by Django 2.1 on 2018-08-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rooms', '0002_room_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
