# Generated by Django 2.1 on 2018-08-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ipfs_hash',
        ),
    ]
