# Generated by Django 2.1 on 2018-08-28 21:19

import app_files.storage.ipfs_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0002_remove_file_ipfs_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=app_files.storage.ipfs_storage.InterPlanetaryFileSystemStorage(), upload_to=''),
        ),
    ]
